export const ONBOARDING_PROVIDER = 'ONBOARDING_PROVIDER';
export const ACCOUNT_PROVIDER = 'ACCOUNT_PROVIDER';
export const CARD_PROVIDER = 'CARD_PROVIDER';
export const PAYMENT_PROVIDER = 'PAYMENT_PROVIDER';
